# -*- coding: utf-8 -*-
"""Exercício 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWQwxZ6OlsBpjxfGDemT62bNXcD27IdM
"""

class ArmaCorpoACorpo:
  def __init__(self, arma: str):
    self.__arma = arma # privado

  def get_arma(self):
    return self.__arma

class PhantomThieves:
  def __init__(self, nome: str, arma: ArmaCorpoACorpo):
    self.__nome = nome # privado
    self.__arma = arma # privado

  def __str__(self):
    return f"{self.__nome} usa {self.__arma.get_arma()}"

class Joker:
  def __init__(self, arma: ArmaCorpoACorpo, equipe: list):
    self.__arma = arma # privado
    self.__equipe = equipe # privado

  def mostrar_equipe(self):
    print(f"Joker usa {self.__arma.get_arma()}. Sua equipe é:")
    for membro in self.__equipe:
        print(f" - {membro}")

if __name__ == "__main__":
  arma_membro1 = ArmaCorpoACorpo("Adaga")
  arma_membro2 = ArmaCorpoACorpo("Chicote")
  arma_membro3 = ArmaCorpoACorpo("Machado")

  membro2 = PhantomThieves("Membro 2", arma_membro2)
  membro3 = PhantomThieves("Membro 3", arma_membro3)

  membro1 = Joker(arma_membro1, [membro2, membro3])

  membro1.mostrar_equipe()