# -*- coding: utf-8 -*-
"""Exercício 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4P6HHexoUz1WH_olW3U5DD6T_vhCnPC
"""

class Personagem:
  def __init__(self, vida: int, resistencia: int):
    self._vida = vida # protegido
    self._resistencia = resistencia # protegido

  def get_vida(self):
    return self._vida

  def set_vida(self, nova_vida):
        self._vida = nova_vida

  def __str__(self):
        return f"Personagem com {self._vida} de vida e {self._resistencia} de resistência"

class Cavaleiro (Personagem):
  def __init__(self, vida: int, resistencia: int, armadura_pesada: bool):
    super().__init__(vida, resistencia)
    self.__armadura_pesada = armadura_pesada # privado

  def __str__(self):
        if(self.__armadura_pesada == True):
          return f"Cavaleiro com armadura pesada, {self._vida} de vida e {self._resistencia} de resistência"
        else:
          return f"Cavaleiro sem armadura pesada, {self._vida} de vida e {self._resistencia} de resistência"

if __name__ == "__main__":
  p1 = Personagem(100, 50)
  print(p1)

  c1 = Cavaleiro(90, 80, True)
  print(c1)

  c2 = Cavaleiro(93, 75, False)
  print(c2)