# -*- coding: utf-8 -*-
"""Exercício 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSzMUHCCIpGqRjQfhpOAZKYRQtB7vUte
"""

from abc import ABC, abstractmethod

class Heroi(ABC):
  def __init__(self, nome: str, funcao: str):
    self._nome = nome # protegido
    self._funcao = funcao # protegido

  @abstractmethod
  def usar_ultimate(self):
        pass  # método abstrato (obrigatório nas classes filhas)

  def __str__(self):
        return f"{self._nome} ({self._funcao})"

class Tanque (Heroi):
  def __init__(self, nome: str):
    super().__init__(nome, "Tanque")

  def usar_ultimate(self):
        print(f"{self._nome} ativou o tanque!")

class Dano (Heroi):
    def __init__(self, nome: str):
        super().__init__(nome, "Dano")

    def usar_ultimate(self):
        print(f"{self._nome} disparou um ataque!")

if __name__ == "__main__":
  herois = [
      Tanque("Heroi 1"),
      Dano("Heroi 2")
  ]

  for heroi in herois:
      print(heroi)
      heroi.usar_ultimate()